### ISSUE TITLE
Проблема с запуском

### ISSUE THREAD

**Issue by Sergik666** [mongooseFlies/django-demo#1]
Отсутсвует файл requirements.txt, в котором должны быть описаны необходимые модули

**Comment by mongooseFlies** [comment]
спасибо)  добавлен requirements.txt

**Comment by Sergik666** [comment]
Не все модули указаны!
![image](https://user-images.githubusercontent.com/913402/60784479-c4f30b80-a157-11e9-8ef6-105ecaa287d3.png)

**Comment by mongooseFlies** [comment]
вы пробовали : 
`pip install -r requirements.txt`
![github](https://user-images.githubusercontent.com/52282436/60806043-95112b80-a18a-11e9-8ca3-87dea2912e0c.png)

![github](https://user-images.githubusercontent.com/52282436/60806498-d2c28400-a18b-11e9-96ab-bfa55cee6eac.gif)
