### ISSUE TITLE
После регистрации невозможно зайти

### ISSUE THREAD

**Issue by Sergik666** [mongooseFlies/django-demo#4]
Пользователь зарегистрирован - логин и пароль: TEST2 и TEST2, но получаем такую страницу

![image](https://user-images.githubusercontent.com/913402/60724344-cbf30180-9f3e-11e9-95cf-ceb5b563632c.png)

**Comment by Sergik666** [comment]
Но логин sergik и пароль 123 работают

![image](https://user-images.githubusercontent.com/913402/60724787-001af200-9f40-11e9-911a-44e340a9d02f.png)

**Comment by mongooseFlies** [comment]
TEST2 уже был в базе данных, я забыл удалить его)
